services:
  slskd:
    image: slskd/slskd:latest
    user: 1000:1000
    container_name: slskd
    ports:
      - "5030:5030" # web UI HTTP
      - "5031:5031" # web UI HTTPS
      - "50300:50300" # listen for incoming connections
    volumes:
      - ./slskd_data:/app/data # Persistent storage for slskd configuration and data
      - ./music:/music:rw # Mount your music library, ensure slskd can read/write
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_USERNAME=${SLSKD_USERNAME}
      - SLSKD_PASSWORD=${SLSKD_PASSWORD}
      - SLSKD_SLSK_USERNAME=${SLSKD_SLSK_USERNAME}
      - SLSKD_SLSK_PASSWORD=${SLSKD_SLSK_PASSWORD}
      - SLSKD_DOWNLOADS_DIR=/music
      - SLSKD_SHARED_DIR=/music
    restart: unless-stopped
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    container_name: navidrome
    ports:
      - "4533:4533" # Navidrome web interface port
    volumes:
      - ./navidrome_data:/data # Persistent storage for Navidrome database and config
      - ./music:/music:ro # Mount your music library (read-only for Navidrome)
    environment:
      - ND_SCANSCHEDULE=1h # Scan for new music every hour
      - ND_LOGLEVEL=trace # Set log level
      - ND_ENABLESHARING=true # Enable sharing features
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: 1000:1000
    ports:
      - "8080:80" # Web UI accessible at http://localhost:8080
    volumes:
      - ./music:/srv # FileBrowser will upload directly to your music library
      - ./filebrowser_data:/database # Persistent FileBrowser config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
  zrok_slskd:
    image: openziti/zrok
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ${HOME}/.zrok:/home/ziggy/.zrok
    environment:
      PFXLOG_NO_JSON: "true"
    command: share reserved "${DOWNLOAD_SERVER_NAME}" --headless --override-endpoint http://slskd:5030
  zrok_navidrome:
    image: openziti/zrok
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ${HOME}/.zrok:/home/ziggy/.zrok
    environment:
      PFXLOG_NO_JSON: "true"
    command: share reserved "${STREAMING_SERVER_NAME}" --headless --override-endpoint http://navidrome:4533